#pragma once
#ifndef DELTA_IN_PORTFOLIO_H
#define DELTA_IN_PORTFOLIO_H
class Assumptions;
class Delta_Puts;
class Nbr_Puts;
class Nbr_Futures;
class Delta_Futures;
/**
* Class to sum up delta of the asset porftolio (includes delta generated by futures and option) 
*/
class Delta_In_Portfolio
{
public:
	struct Objects_Needed
	{
		Assumptions* assumptions;
		Delta_Puts* delta_puts;
		Nbr_Puts* nbr_puts;
		Nbr_Futures* nbr_futures;
		Delta_Futures* delta_futures;
	} objects_needed;
	struct Characteristics
	{
		double length_of_option_contract;
		double sell_at_time_to_expiry;
	} characteristics;
	double * asset_delta;
	double ** tab;
	void init_tab();
	Delta_In_Portfolio(
		Assumptions* assumptions,
		Delta_Puts* delta_puts,
		Nbr_Puts* nbr_puts,
		Nbr_Futures* nbr_futures,
		Delta_Futures* delta_futures
		);
	~Delta_In_Portfolio(void);
};
#endif