// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "in_bom.h"

/////////////////////////////////////////////////////////////////////////////
// CIn_bom

IMPLEMENT_DYNCREATE(CIn_bom, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIn_bom properties

/////////////////////////////////////////////////////////////////////////////
// CIn_bom operations
