#pragma once
#ifndef RHO_IN_PORTFOLIO_H
#define RHO_IN_PORTFOLIO_H
class Assumptions;
class Rho_Puts;
class Nbr_Puts;
class Nbr_Futures;
class Rho_Futures;
class Nbr_Swaps;
class Rho_Swaps;
/**
* Class to sum up delta of the asset porftolio (includes delta generated by futures and option) 
*/
class Rho_In_Portfolio
{
public:
	struct Objects_Needed
	{
		Assumptions* assumptions;
		Rho_Puts** rho_puts_glob;
		Nbr_Puts** nbr_puts_glob;
		Nbr_Futures** nbr_futures_glob;
		Rho_Futures** rho_futures_glob;
		Nbr_Swaps* nbr_swaps;
		Rho_Swaps* rho_swaps;
	} objects_needed;
	struct Characteristics
	{
		double length_of_option_contract;
		double sell_at_time_to_expiry;
	} characteristics;

	double * asset_rho;
	int nb_index;
	double ** tab;
	void init_tab();
	Rho_In_Portfolio(
		Assumptions* assumptions,
		Rho_Puts** rho_puts_glob,
		Nbr_Puts** nbr_puts_glob,
		Nbr_Futures** nbr_futures_glob,
		Rho_Futures** rho_futures_glob,
		Nbr_Swaps* nbr_swaps,
		Rho_Swaps* rho_swaps,
		int nb_index
		);
	~Rho_In_Portfolio(void);
};
#endif