#pragma once

#define PROD_NAME_BL	8
#define INIT_CHARGE_BL	9
#define FUND_NAME_BL	10
#define CURRENCY_BL	11
#define ISSUE_DATE_BL	12
#define NB_DATE_BL 13
#define INV_DATE_BL	14
#define DEF_PERIOD_BL 15
#define DURATION_BL	16
#define ANNUITY_BEGIN_BL	17
#define PROD_PREM_TYPE_BL	18
#define PREMIUM_BL 19
#define AMOUNT_INV_BL	20
#define FREQ_MODE_BL	21
#define WITHDRAWAL_RATE_BL	22
#define INV_PROTECTION_BL	23
#define BENEFIT_INCREASE_FACTOR_BL	24
#define WITHDRAWAL_MODE_DISCOUNT_BL 25
#define GUARANTEE_BL	26
#define ACCUM_WITHDRAWAL_AMOUNT_BL	27
#define PERF_BONUS_AMOUNT_BL	28
#define AV_BEF_BEF_BL	29
#define AV_AFTER_BEF_BL	30
#define AV_AFTER_AFTER_BL	31
#define BASE_CAPITAL_BL	32
#define FUND_UNIT_BEF_BEF_BL	33
#define FUND_UNIT_AFTER_BEF_BL	34
#define FUND_UNIT_AFTER_AFTER_BL 35

#define MAX_INFORCE_COLS_BL_RTS_SWISS_01 36
