#pragma once

#define  PRODUCT_BL_LUX                       0
#define  VALN_DATE_BL_LUX                     1
#define  FUND_FEES_BL_LUX                     2
#define  INFO_BL_LUX                          3
#define  PROD_CODE_BL_LUX                     4
#define  EHC_BL_LUX                           5
#define  NEW_BUSINESS_BL_LUX                  6
#define  POLICY_ID_BL_LUX                     7
#define  PERSON_ID_1_BL_LUX                   8
#define  PERSON_ID_2_BL_LUX                   9
#define  PROD_CODE2_BL_LUX                    10
#define  INIT_CHARGE_BL_LUX                   11
#define  ONGOING_ACQUI_CHARGE_BL_LUX          12
#define  ACCOUNT_CODE_BL_LUX                  13
#define  CURRENCY_BL_LUX                      14
#define  GENDER_1_BL_LUX                      15
#define  DATE_BIRTH_1_BL_LUX                  16
#define  DATE_DEATH_1_BL_LUX                  17
#define  ISSUE_AGE_1_BL_LUX                   18
#define  GENDER_2_BL_LUX                      19
#define  DATE_BIRTH_2_BL_LUX                  20
#define  DATE_DEATH_2_BL_LUX                  21
#define  ISSUE_AGE_2_BL_LUX                   22
#define  TECHNICAL_ISSUE_AGE_BL_LUX           23
#define  ISSUE_DATE_BL_LUX                    24
#define  INV_DATE_BL_LUX                      25
#define  DEF_PERIOD_BL_LUX                    26
#define  DURATION_BL_LUX                      27
#define  ANNUITY_BEGIN_DATE_BL_LUX            28
#define  PREMIUM_PAYMENT_MODE_BL_LUX          29
#define  INSURANCE_PREMIUM_BL_LUX             30
#define  AMOUNT_INVESTED_BL_LUX               31
#define  WITHDRAWAL_MODE_BL_LUX               32
#define  CONVERSION_RATE_BL_LUX               33
#define  ROLLUP_RATE_BL_LUX                   34
#define  DEF_GUAR_BL_LUX                      35
#define  INV_PROTECTION_BL_LUX                36
#define  BENEFIT_INCREASE_FACTOR_BL_LUX       37
#define  WITHDRAWAL_MODE_DISCOUNT_BL_LUX      38
#define  GMDB_RIDER_BL_LUX                    39
#define  GMDB_MODE_BL_LUX                     40
#define  GMDB_MAX_AGE_BL_LUX                  41
#define  GMDB_DURATION_BL_LUX                 42
#define  GMDB_LUX                             43
#define  CURR_GMWB_BL_LUX                     44
#define  ACCUM_WITHDRAWAL_AMOUNT_BL_LUX       45
#define  PERF_BONUS_BL_LUX                    46
#define  PERF_BONUS_LEVEL_BL_LUX              47
#define  PERF_BONUS_TYPE_BL_LUX               48
#define  ADD_ACCUM_WITHDRAWAL_AMOUNT_BL_LUX   49
#define  PERF_BONUS_AMOUNT_BL_LUX             50
#define  ACCOUNT_VALUE_BL_LUX                 51
#define  BASE_CAPITAL_BL_LUX                  52
#define  FUND_UNITS_BL_LUX                    53
#define  UNIT_PRICE_BL_LUX                    54
#define  REINSURANCE_PREMIUM_BL_LUX           55
#define  FUND_CHARGE_BL_LUX                   56
#define  UPFRONT_COMM_BL_LUX                  57
#define  TRAIL_COMM_BL_LUX                    58

#define  MAX_INFORCE_COLS_BL_LUX              59
