#pragma once

#define  PRODUCT_TYPE_LIE_RST_DE	0
#define  VALN_DATE_LIE_RST_DE	1
#define  FUND_FEES_LIE_RST_DE	2
#define  INFO_LIE_RST_DE	3
#define  PROD_CODE_LIE_RST_DE	4
#define  EHC_LIE_RST_DE	5
#define  NEW_BUSINESS_LIE_RST_DE	6
#define  POLICY_ID_LIE_RST_DE	7
#define  PERSON_ID_1_LIE_RST_DE	8
#define  Product_Code_LIE_RST_DE	9	//to check again
#define  INIT_CHARGE_LIE_RST_DE	10
#define  ACCOUNT_CODE_LIE_RST_DE	11
#define  CURRENCY_LIE_RST_DE	12
#define  GENDER_1_LIE_RST_DE	13
#define  DATE_BIRTH_1_LIE_RST_DE	14
#define  ISSUE_AGE_1_LIE_RST_DE	15
#define  ISSUE_DATE_LIE_RST_DE	16
#define  NB_DATE_LIE_RST_DE	17
#define  INV_DATE_LIE_RST_DE	18
#define  DEF_PERIOD_LIE_RST_DE	19
#define  DURATION_LIE_RST_DE	20
#define  ANNUITY_BEGIN_DATE_LIE_RST_DE	21
#define  PREMIUM_PAYMENT_MODE_LIE_RST_DE	22
#define  INSURANCE_PREMIUM_LIE_RST_DE	23
#define  AMOUNT_INVESTED_LIE_RST_DE	24
#define  WITHDRAWAL_MODE_LIE_RST_DE	25
#define  CONVERSION_RATE_LIE_RST_DE	26
#define  DEF_GUAR_LIE_RST_DE	27
#define  BENEFIT_INCREASE_FACTOR_LIE_RST_DE	28
#define  GMDB_LIE_RST_DE	29
//#define  WITHDRAWAL_MODE_DISCOUNT_LIE_RS_CHF	35
#define  CURR_GMWB_LIE_RST_DE	30
#define  ACCUM_WITHDRAWAL_AMOUNT_LIE_RST_DE	31
#define  PERF_BONUS_AMOUNT_LIE_RST_DE	32
#define  ACC_VAL_BEF_BEF_LIE_RST_DE	33
#define  ACC_VAL_AFT_BEF_LIE_RST_DE	34
#define  ACC_VAL_AFT_AFT_LIE_RST_DE	35
#define  BASE_CAPITAL_LIE_RST_DE	36
#define  FUND_UNITS_BEF_BEF_LIE_RST_DE	37
#define  FUND_UNITS_AFT_BEF_LIE_RST_DE	38
#define  FUND_UNITS_AFT_AFT_LIE_RST_DE	39
#define  UNIT_PRICE_LIE_RST_DE	40

#define MAX_INFORCE_COLS_LIE_RST_DE_01	41